# Generated by Django 5.0.2 on 2024-02-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('pizza_size', models.TextField()),
                ('crust', models.TextField()),
                ('sauce', models.TextField()),
                ('toppings', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
    ]
