# Generated by Django 5.0.2 on 2024-02-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_size',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='sauce',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.TextField(null=True),
        ),
    ]
