# Generated by Django 5.0.2 on 2024-02-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_topping_remove_pizza_pizza_size_remove_pizza_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.CharField(choices=[('pepperoni', 'Pepperoni'), ('chicken', 'Chicken'), ('ham', 'Ham'), ('pineapple', 'Pineapple'), ('peppers', 'Peppers'), ('mushrooms', 'Mushrooms'), ('onions', 'Onions')], max_length=10, null=True),
        ),
    ]
