# Generated by Django 5.0.2 on 2024-02-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_cheese_pizzasize_sauce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='crust',
            field=models.CharField(choices=[('normal', 'Normal'), ('thin', 'Thin'), ('thick', 'Thick'), ('gluten_free', 'Gluten Free')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True),
        ),
    ]
